{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "newchart.serviceAccountName" . }}
  labels:
{{ include "newchart.labels" . | indent 4 }}
{{- end -}}
